In [ ]:
# To import csv file
from google.colab import files
uploaded = files.upload()

In [ ]:
# Assuming you have already uploaded the file using files.upload()
# If not, run the previous cell to upload the file first
# To view the raw data in csv
for fn in uploaded.keys():
  print('Contents of {name}:'.format(name=fn))
  print(uploaded[fn].decode('utf-8'))

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2

In [ ]:
df = pd.read_csv('Walmart.csv', encoding_errors='ignore')
df.shape

(10051, 11)

In [ ]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

# **DATA CLEANING**

In [ ]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [ ]:
# All duplicates
df.duplicated().sum()

np.int64(51)

In [ ]:
# To drop duplicates
df.drop_duplicates(inplace=True)

df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(10000, 11)

In [ ]:
# No of null values
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [ ]:
# Remove/dropping all rows with missing records (here null values)
df.dropna(inplace=True)

#verify
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [ ]:
df.shape

(9969, 11)

In [ ]:
# To convert the 'unit_price' dtype from object into float - we got error because of the dollar sign
df['unit_price'].astype(float)

ValueError: could not convert string to float: '$74.69'

In [ ]:
df['unit_price'].str.replace('$', '')

df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [ ]:
# Replace $ with nothing and convert dtype
df['unit_price'] = df['unit_price'].str.replace('$', '').astype(float)
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

Above cell executed twice, ignore output, go on with the project

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   object
 2   City            9969 non-null   object
 3   category        9969 non-null   object
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   object
 7   time            9969 non-null   object
 8   payment_method  9969 non-null   object
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 1.2+ MB

In [ ]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='object')

In [ ]:
# Creating a new column total = unit_price * quantity
df['total'] = df['unit_price'] * df['quantity']
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

# **EXPORTING Data to MYSQL**

In [ ]:
# mysql tool kit - to connect with mysql and setup everything

# pymysql - this will work as an adapter
# sqlalchemy , create_engine

import pymysql
from sqlalchemy import create_engine

In [ ]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 3.8 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [ ]:
import pymysql
from sqlalchemy import create_engine

The code in the above cell imports two necessary components for interacting with a MySQL database using Python:

import pymysql: This line imports the pymysql library, which is a Python driver for MySQL databases. It allows Python to connect to and execute commands on a MySQL server.

from sqlalchemy import create_engine: This line imports the create_engine function from the sqlalchemy library. SQLAlchemy is a powerful SQL toolkit and Object-Relational Mapper (ORM) for Python. The create_engine function is used to establish a connection to a database.
Together, these imports prepare your environment to connect to and work with a MySQL database from your notebook.

In [ ]:
#mysql - when you are hosting in local machine - remember below
#host: localhost
#port: 3306
#user: root
#password: enter your password

In [ ]:
df.shape

(9969, 12)

In [ ]:
df.to_csv('Walmart_clean_data.csv', index=False)  # To save the cleaned data into a csv and then use in mysql if you dont want to connect directly

# in colab, if files section in the left side, you can download the saved file

Now we need to create a table in sql and then upload the data which is a long process. Instead we can use a simple pandas df statement to export the data into mySQL

In [ ]:
help(create_engine)

# Connection to MYSQL

In [ ]:
#mysql connection

engine_mysql = create_engine('mysql+pymysql://root:Mysql@localhost:3306/walmart_db')

try:
  engine_mysql
  print('Connection Successful')
except:
  print('Connection Failed')

Connection Successful

In [ ]:
help(df.to_sql)

In [ ]:
df.to_sql(name='walmart',con=engine_mysql, if_exists='append', index=False)